from pydantic import BaseModel, Field
from typing import List, Literal, Optional
from uuid import uuid4

class ToolCallInfo(BaseModel):
    tool_name: str = Field(..., description="The name of the tool")
    arguments: dict = Field(default_factory=dict, description="The arguments used in the tool.")

class ChatRequest(BaseModel):
    user_id: str = Field(..., description="The unique identifier of the user.")
    session_id: str = Field(..., description="The session identifier for conversation threading.")
    user_message: str = Field(..., min_length=1, max_length=10000, description="The actual text message from the user.")

class ChatResponse(BaseModel):
    user_id: str = Field(..., description="The unique identifier of the user.")
    session_id: str = Field(..., description="The session identifier.")
    tool_calls_made: List[ToolCallInfo] = Field(
        default_factory=list, 
        description="A list of tool names invoked by the agent to fulfill the request."
    )
    tokens_used: Optional[int] = Field(..., description="The total number of tokens generated by the LLM.")
    message: str = Field(..., description="The final natural language response from the agent.")

class Message(BaseModel):
    role: Literal['system', 'assistant', 'user', 'tool'] = Field(..., description="The role of the message")
    content: Optional[str] = Field(None, description="The content of the message")
    user_id: Optional[str] = Field(None, description="The unique identifier of the user.")
    session_id: Optional[str] = Field(default_factory=lambda: str(uuid4()), description="The session identifier.")
    tokens_used: Optional[int] = Field(None, description="The total number of tokens generated by the LLM.")
    tool_calls: Optional[List[dict]] = None
    tool_call_id: Optional[str] = None

class AgentResponse(BaseModel):
    content: Optional[str] = Field(None, description="The content generated by the agent")
    tool_calls: Optional[List[dict]] = Field(None, description="The tool calls")
    usage: Optional[dict] = Field(None, description="A dict that contains the token usage of the response")
    finish_reason: Optional[str] = Field(None, description="The finish reason of the response")
